run_config:
  name: random-forest-featset-1
  author: Xinran Wang
  version: default
  description: Classifies clouds into one of two types.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data

create_dataset:
  load_data:
    data_path: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
    header: None
    names:
    - visible_mean
    - visible_max
    - visible_min
    - visible_mean_distribution
    - visible_contrast
    - visible_entropy
    - visible_second_angular_momentum
    - IR_mean
    - IR_max
    - IR_min

generate_features:
  calculate_norm_range:
    IR_norm_range:
      min_col: IR_min
      max_col: IR_max
      mean_col: IR_mean
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy

analysis:
  target_name: class

train_model:
  model: RandomForestClassifier
  train_test_split:
    test_size: 0.4
    random_state: 42
  target_name: class
  initial_features:
    - log_entropy
    - IR_norm_range
    - entropy_x_contrast
  test_size: 0.4
  n_estimators: 10
  max_depth: 10

score_model:
  initial_features:
    - log_entropy
    - IR_norm_range
    - entropy_x_contrast

evaluate_performance:
  target_name: class

aws:
  sts: True
  upload: True
  bucket_name: uaq7345-hw2
  prefix: experiments

